### ISSUE TITLE
深蓝学院 ORB-SLAM公开课的讲座PPT

### ISSUE THREAD

**Issue by psyduck04** [DreamWaterFound/self_commit_ORB-SLAM2#2]
你好！非常感谢你在深蓝学院进行ORB-SLAM论文研读的分享！在深蓝官网目前找不着公开课的ppt，请问能否再上传一下公开课的ppt呢？再次感谢！

**Comment by xmyqsh** [comment]
高翔, 张涛, 颜沁睿, 刘毅, 视觉SLAM十四讲：从理论到实践, 电子工业出版社

**Comment by DreamWaterFound** [comment]
不好意思……我这隔了快一个月才看到……

PPT在下面：

[ORB-SLAM(v1,v2)论文带读-东北大学-刘国庆.pdf](https://github.com/DreamWaterFound/self_commit_ORB-SLAM2/files/4151258/ORB-SLAM.v1.v2.-.-.pdf)

其实PPT的后半部分做得还是很草率，我觉得参考价值可能不大，还是直接看论文收获来得更多些 :joy:

**Comment by xmyqsh** [comment]
http://www.computervisionblog.com/2016/01/why-slam-matters-future-of-real-time.html
