### ISSUE TITLE
关于ORB-SLAM的疑问

### ISSUE THREAD

**Issue by qimao7213** [DreamWaterFound/self_commit_ORB-SLAM2#3]
你好，我听了您在深蓝学院的ORB-SLAM论文带读视频课，现在有两个问题想请教一下。
1.局部地图由是几个关键帧和对应的地图点组成的吗？局部地图也是在不断更新的。那一般局部地图的规模一般有多大呢？关键帧一般有几帧？
2.对于初始化时的Full-BA，还是没有很理解到底是那些帧进行一个BA操作，起到了一个什么效果？
3.ORB-SLAM，是一个很大（冗余）的系统，为了保证精确性之类的，感觉里面做了很多工作，那你认为这个系统是如何在保证优秀性能、复杂运算的同时，还保证了良好的实时性呢？是计算机性能吗，代码的编写吗还是线程的分配？

然后，您在介绍的时候提到在做动态环境下的SLAM研究，我也对这一部分比较感兴趣，刚开始，看了一些论文。您能对于动态环境下的SLAM谈谈您的看法吗？
谢谢

**Comment by DreamWaterFound** [comment]
不好意思……这一年没咋看这个仓库，才看到提问

1、“局部地图由是几个关键帧和对应的地图点组成的吗？”  -- 对
     “那一般局部地图的规模一般有多大呢？关键帧一般有几帧？” --  不确定，看其他关键帧和当前关键帧的共视关系而定
2、一个是优化初始化时的关键帧（单目时是两帧，非单目时是一帧，此时其实也就没优化）的位姿，以及所有创建的初始地图点的位置。你会发现ORB-SLAM2的基本思路就是一层一层的BA组成的，从最开始的Motion-only BA，到Local BA，以及回环检测后的Global BA，其基本思想都是通过使用越来越多的约束逐渐对相机位姿求精。所以初始化后要先尽可能得到精确的关键帧/地图点位姿/位置，为后面相机位姿的准确估计打下良好基础。
3、“线程的分配”是一点，不过不是原创，ORB-SLAM1提出的时候已经有许多研究都利用上多线程了。我觉得最根本的原因是共视关系/关键帧（在那个时候共视关系还是比较新潮的思想）的使用，论文中也有提到。
4、动态环境问题，我是觉得视觉方法落地比较难，多传感器结合才是王道。
