### ISSUE TITLE
师兄，我想问问ORBslam如何取得当前相机的位姿矩阵呀？

### ISSUE THREAD

**Issue by shiniankanchaige** [DreamWaterFound/self_commit_ORB-SLAM2#4]

**Comment by DreamWaterFound** [comment]
https://github.com/DreamWaterFound/self_commit_ORB-SLAM2/blob/master/Examples/RGB-D/rgbd_tum.cc#L129

这个函数调用后会返回当前帧的位姿，不过作者给的Examples中并没有用到
